version: "3.8"
services:
    kaypoh-frontend-dev:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - 3000:3000
        volumes:
            - ./src:/app/src
        environment:
            - WATCHPACK_POLLING=true
        stdin_open: true
        tty: true
