version: "3.8"
services:
    kaypoh-frontend-prod:
        build:
            context: .
            dockerfile: Dockerfile.prod
            args:
                - NODE_ENV='production'
        ports:
            - 3001:80
        stdin_open: true
        tty: true
